### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'pack'

### ISSUE THREAD

**Issue by gearcapitan** [punk-security/dnsReaper#118]
with python 2

<img width="446" alt="image" src="https://user-images.githubusercontent.com/13740942/188023700-b4964878-ef66-4c45-bd61-8ef49bda0db0.png">

whit python 3 

<img width="446" alt="image" src="https://user-images.githubusercontent.com/13740942/188023716-398a8471-6453-43c3-afb4-c937465c92a0.png">

**Comment by danieloateslee** [comment]
@gearcapitan the screen shot are both the same for python2 and python3 ... can you please try the following

python3 main.py single --domain {{domain name}}

It shouldn't work in python2 as it was designed for python3 only.

**Comment by gearcapitan** [comment]
this is the results
<img width="323" alt="image" src="https://user-images.githubusercontent.com/13740942/188176402-17ed354c-80d8-4944-aa92-e610a2518792.png">

**Comment by noopec** [comment]
Try running **python3** as mentioned by Dan in the post above your screenshot shows **python2**. Our tool only supports **python3**. Try running **python3 main.py single -- domain**

**Comment by gearcapitan** [comment]
<img width="430" alt="image" src="https://user-images.githubusercontent.com/13740942/188214976-e93ab2cd-95dc-4943-b8f1-04b13b6ad40d.png">

**Comment by SimonGurney** [comment]
Hmmm.

My thought is that a thread in our pool is not being terminated, but I don't understand why.  

To get to the results but, which you are, all threaded tasks should have completed.

Dask had a kind of similar error and added some explicit pool teardown.

 https://github.com/dask/dask/issues/5806

Can you share some env info?

You are using python3.10.  It would be good to know the full version number.

Also, how many cpus do you have and is it x86 or arm?

**Comment by SimonGurney** [comment]
https://stackoverflow.com/questions/70515134/graceful-cleanup-for-multiprocess-pool-python suggests we can explicitly close the pool after the map.  We'll test this and ask you to pull that branch if that's ok @gearcapitan?

**Comment by SimonGurney** [comment]
Ok I've done that, can you switch to the fix-close-pool branch and try your scan again?

```
git pull
git checkout fix-close-pool
```

**Comment by SimonGurney** [comment]
@gearcapitan are you ok to test?
