### ISSUE TITLE
Overwriting output file Path (--out) 

### ISSUE THREAD

**Issue by mohsinenar** [punk-security/dnsReaper#125]
I was trying to integrate dnsReaper with another security automation tool. 
I used python to run the dnsReaper and Read the output as a JSON later.
something like this.
```python
output_file = tempfile.NamedTemporaryFile(suffix='.json')
command = ['python3', '/dnsReaper/main.py','single', '--domain', domain, '--out-format', 'json', '--out', output_file.name]
subprocess.run(command, check=True)
```
however, the tool always writes the output in a different path than the one I provided with `output_file.name`.
This is because the following line in  'output.py' always adds the extension (.josn | .csv) to the file path.
```python
self.path = f"{path}.{format}"
```

**Comment by mohsinenar** [comment]
A did a small change to the output,py file to make it work for me.
```python
self.path = path if path.endswith(format) is True else f"{path}.{format}"
```

Should I create a PR?

**Comment by SimonGurney** [comment]
That looks like a great contribution.

If you raise a PR I'll give it a quick test and  approve it for merging :)

**Comment by mohsinenar** [comment]
@SimonGurney  I created a PR #126
