### ISSUE TITLE
Large Amounts of Subdomains in File

### ISSUE THREAD

**Issue by harbinc** [punk-security/dnsReaper#169]
I have a program that I monitor that has over 100k+ subdomains. I will be using dnsReaper with the file option. Are there any recommendations for scanning such a large number of domains in a text file? And should I be concerned with DNS request timeouts or getting rate limited? If so please give me your best advise on how to scan a large number of sub domains in a text file and to do so without getting my DNS request blocked. 

Thanks for the great app. I love it, and have tested on other projects.

**Comment by SimonGurney** [comment]
Hey :)

Have you tried setting the parallelism much lower? The default is 30 subdomains at a time.

```
--parallelism 10
```

**Comment by SimonGurney** [comment]
FYI we've changed the behaviour in the new async runtime ton use 6 different public dns servers and load balance across them to overcome rate-limiting a little better
