### ISSUE TITLE
False positive on a GoDaddy domain scan on 2.0.0

### ISSUE THREAD

**Issue by isvalga** [punk-security/dnsReaper#193]
Hello,

With the update to version 2.0.0 we have encountered a false positive when performing an API scan against GoDaddy.

These are the results with version 1.10.0:

```
Testing with 61 signatures


We found 0 takeovers ☠️

⏱️  We completed in 6.85 seconds
...Thats all folks!
```

And these are the results with versión 2.0.0, same configuration, same url (not real url for this example ):

```
Testing with 62 signatures

DNS Resolving: (Feedback per 100 resolves)
[ . = success, + = non-existent domain, x = error (likely rate-limiting)]
.

We found 1 takeovers ☠️
-- DOMAIN 'www.anonymizedurl.com' :: SIGNATURE '_generic_cname_found_doesnt_resolve' :: CONFIDENCE 'POTENTIAL'
CNAME: @

⏱️  We completed in 2.91 seconds
...Thats all folks!
```

The same in another format:

```
[
  {
    "domain": "www.anonymizedurl.com",
    "signature": "_generic_cname_found_doesnt_resolve",
    "info": " The defined domain has a CNAME record configured but the CNAME does not resolve. You should look to see if you can register or takeover this CNAME.",
    "confidence": "POTENTIAL",
    "a_records": [],
    "aaaa_records": [],
    "cname_records": [
      "@"
    ],
    "ns_records": [],
    "more_info_url": ""
  }
]
```

The dns entry is not configured in the Godaddy domain and also, it does not make sense that there is a CNAME for @.

Could you please check?

Thanks for the tool, and thanyou in advance. BR

**Comment by SimonGurney** [comment]
Thanks for letting us know, and that's super useful information in the issue.

We'll see if we can reproduce here and let you know. 

Do you have a cname on that record, or some GoDaddy alias equivalent?

**Comment by isvalga** [comment]
We have this two DNS entrys related to the issue:

- This is the only @ entry, and is the one wich references our domain:

![image](https://github.com/user-attachments/assets/bba99f69-f81f-4bea-982e-67098de42d3c)

- And this one, wich is an standar CNAME www DNS entry:

![image](https://github.com/user-attachments/assets/33ac8db8-1446-456b-8071-b13c8aaf827b)

**Comment by SimonGurney** [comment]
Super thanks, and does that cname for www point at this domain or off somewhere else?

**Comment by isvalga** [comment]
same domain, in our example:

CNAME    www    anonymizedurl.com

**Comment by SimonGurney** [comment]
So GoDaddy have decided people with less than 10 domains cannot access the API, which breaks our ability to test.

Can you validate this fix for us? It's on branch  godaddy-apex-fix

**Comment by isvalga** [comment]
Hello Simon, I have already test godaddy-apex-fix, and it is working properly:

![image](https://github.com/user-attachments/assets/83a02fc9-5ca2-4810-af6c-e56c0ab88cc6)

**Comment by SimonGurney** [comment]
Ah fantastic, thanks for testing!

We've got an email exchange going with GoDaddy around getting API access back. We'll add some notes to the Docs around their new API restrictions and then get this merged

**Comment by isvalga** [comment]
Okey, thank you very much!
