### ISSUE TITLE
Support for SecurityTrails

### ISSUE THREAD

**Issue by kero3009destiny** [punk-security/dnsReaper#82]
SecurityTrails has a powerful free API for reconnaissance, I'm not sure if it fully fits dnsReaper's scope but I think it could be useful.

API documentation is at https://docs.securitytrails.com/docs/overview

**Comment by SimonGurney** [comment]
Thanks for the comment.

We use the whois python library which is reasonably complete but the suffers from rate limiting issues and doesn't have full tld coverage.  Ill test that service for coverage and rate limiting :)

**Comment by SimonGurney** [comment]
Rate limiting of whois data isn't actually a problem for us so we have no need for integration.  If you can think of a use case then please reopen

**Comment by kero3009destiny** [comment]
My suggestion for SecurityTrails was mostly based on subdomain discovery rather than WHOIS queries

**Comment by SimonGurney** [comment]
Ah I see, so subdomain enumeration via this API endpoint?
 https://docs.securitytrails.com/reference/domain-subdomains

We could look to do this.  We were already hoping to add a provider for projectdiscovery and project sonar.

I'll reopen
